---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86138.
--- DateTime: 2026-04-20 19:14
---

-- 锁的key
local key = KEYS[1]
-- 当前线程标示
local threadId = ARGV[1]

-- 获取锁中的线程标示 get key
local id = redis.call("get", key)
-- 比较线程标示与锁中的标示是否一致
if (id == ARGV[1]) then
    -- 释放锁 del key
    return redis.call("del", key)
end
